# -*- coding: utf-8 -*-
"""ifls_short_completed.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19KyYtPupNPDpYdqZ6C1yskPa2q3xWR5n

# Import packages
"""

library(foreign)

library(plyr)

library(dplyr)

library(ggplot2)

library(tidyr)

install.packages("epiR", repos='http://cran.us.r-project.org')

library(epiR)

install.packages("gmodels", repos='http://cran.us.r-project.org')

library(gmodels)

install.packages("gplots", repos='http://cran.us.r-project.org')

library(gplots)

options(scipen = 999)

"""# Variable preparation - Select only related variable needed then scoring to each ID's"""

#Diabetes Dependent Variable and medication

b3b_cd3 <- read.dta("b3b_cd3.dta")
head(b3b_cd3)
str(b3b_cd3)
diabetes_medication <- b3b_cd3 %>%
                select(hhid14_9, hhid14, pidlink, cdtype, cd05, cd09) %>%
                filter(cdtype == 'B')
diabetes_medication <- rename(diabetes_medication, "diabetes" = cd05, "medication" = cd09)
head(diabetes_medication)
str(diabetes_medication)
summary(diabetes_medication)

#Physical Activity

b3b_kk2 <- read.dta("b3b_kk2.dta")
head(b3b_kk2)
str(b3b_kk2)
summary(b3b_kk2)

activity <- b3b_kk2 %>%
    select(pidlink, kktype, kk02m, kk02n1, kk02n2, kk02o)

# Activity first phase --> create "imperfect" pysical activity category by select pidlink who classified into certain classes
# "Imperfect" here means the categorization process did not involve MET calculation
#There are so many NA's in the result because it is "imperfect". Need to calculate MET estimation

activity_completed <- activity %>%
    mutate(activity_categorized = case_when(kk02m == "1:Yes" & kktype == 'A' & kk02o >= 3 & kk02n1 == "2:>= 2 hours" ~ "High",
                                            kk02m == "1:Yes" & kktype == 'A' & kk02o >= 3 & kk02n1 == "1:< 2 hours" & kk02n2 == "12:>= 30 minutes" ~ "Moderate",
                                            kk02m == "1:Yes" & kktype == 'A' & kk02o >= 3 & kk02n1 == "2:>= 2 hours" ~ "Moderate",
                                            kk02m == "1:Yes" & kktype != 'A' & kk02o >= 5 & kk02n1 == "1:< 2 hours" & kk02n2 == "12:>= 30 minutes" ~ "Moderate",
                                            kk02m == "1:Yes" & kktype != 'A' & kk02o >= 5 & kk02n1 == "2:>= 2 hours" ~ "Moderate",
                                            kk02m == "3:Never" ~ "Low"),
                                  activity_categorized = factor(activity_categorized, levels=c("High", "Moderate", "Low"))) %>%
    rename("type" = kktype, "active" = kk02m, "hours" = kk02n1, "minutes" = kk02n2, "days" = kk02o) %>%
    mutate(activity_type = revalue(type, c("A" = "Vigorous",
                                           "B" = "Moderate",
                                           "C" = "Walking"))) %>%
    select(-type)

head(activity_completed)

# Second phase --> create column for calculating MET estimation
# Create column minute_numbers for estimation then convert long data to wide data

ceiling <- c("11:< 30 minutes" = 29,
             "12:>= 30 minutes" = 119,
             "21:< 4 hours" = 239,
             "22:>= 4 hours" = 240)

median <- c("11:< 30 minutes" = 20,
            "12:>= 30 minutes" = 75,
            "21:< 4 hours" = 180,
            "22:>= 4 hours" = 240)

floor <- c("11:< 30 minutes" = 10,
           "12:>= 30 minutes" = 30,
           "21:< 4 hours" = 120,
           "22:>= 4 hours" = 240)

activity_wide <- activity_completed %>%
    mutate(minutes_number = revalue(minutes, floor)) %>% #CHANGE ESTIMATION HERE
    gather(variable, value, -pidlink, -activity_type) %>%
    unite(temp, activity_type, variable) %>%
    spread(temp, value) %>%
    mutate(Vigorous_days = as.numeric(Vigorous_days),
           Moderate_days = as.numeric(Moderate_days),
           Walking_days = as.numeric(Walking_days),
           Vigorous_minutes_number = as.numeric(Vigorous_minutes_number),
           Moderate_minutes_number = as.numeric(Moderate_minutes_number),
           Walking_minutes_number = as.numeric(Walking_minutes_number))

## Unselect imperfect activity_categorized from first phase

activity_wide_replaced_zero <- activity_wide %>%
    select(-Moderate_activity_categorized, -Walking_activity_categorized, -Vigorous_activity_categorized)

activity_wide_replaced_zero[is.na(activity_wide_replaced_zero)] <- 0

head(activity_wide_replaced_zero)
summary(activity_wide_replaced_zero)

# Calculate total days and total MET estimation

activity_total <- activity_wide_replaced_zero %>%
    mutate("total_days" = Vigorous_days + Moderate_days + Walking_days,
           "walking_MET" = 3.3 * Walking_days * Walking_minutes_number,
           "moderate_MET" = 4.0 * Moderate_days * Moderate_minutes_number,
           "vigorous_MET" = 8.0 * Vigorous_days * Vigorous_minutes_number) %>%
    mutate("total_MET" = walking_MET + moderate_MET + vigorous_MET)

head(activity_total)
summary(activity_total)

# Calculate and categorized each person ID's physical activity tipe based on IPAQ

activity_calculated <- activity_total %>%
    mutate(activity_calc_categorized = case_when((Vigorous_days >= 3 & Vigorous_hours == "2:>= 2 hours")
                                                 |(Vigorous_days >= 3 & vigorous_MET >= 1500)
                                                 |(total_days >= 7 & total_MET >= 3000) ~ "0:High",
                                                 (Vigorous_days >= 3 & Vigorous_hours == "1:< 2 hours" & Vigorous_minutes == "12:>= 30 minutes")
                                                 |(Vigorous_days >= 3 & Vigorous_hours == "2:>= 2 hours")
                                                 |(total_days >= 5 & Moderate_hours == "1:< 2 hours" & Moderate_minutes == "12:>= 30 minutes")
                                                 |(total_days >= 5 & Moderate_hours == "2:>= 2 hours")
                                                 |(total_days >= 5 & Walking_hours == "1:< 2 hours" & Walking_minutes == "12:>= 30 minutes")
                                                 |(total_days >= 5 & Walking_hours == "2:>= 2 hours")
                                                 |(total_days >= 5 & total_MET >= 600) ~ "1:Moderate",
                                                 TRUE ~ "2:Low"),
                                  activity_calc_categorized = factor(activity_calc_categorized, levels=c("0:High", "1:Moderate", "2:Low")))

activity_categorized <- activity_calculated %>%
    select(pidlink, "activity_cat" = activity_calc_categorized)

head(activity_categorized)
summary(activity_categorized)

#Insurance data

b3b_ak1 <- read.dta("b3b_ak1.dta")
head(b3b_ak1)
tail(b3b_ak1)
insurance <- b3b_ak1 %>%
    select(pidlink, ak01) %>%
    distinct()
insurance <- rename(insurance, "insurance" = ak01)
head(insurance)
str(insurance)
summary(insurance)

# Sex, age and marstat

b3a_cov <- read.dta("b3a_cov.dta")
head(b3a_cov)
sex_age_marstat <- b3a_cov %>%
    select(hhid14_9, hhid14, pidlink, sex, age, marstat)
head(sex_age_marstat)

# Residence

bk_sc1 <- read.dta("bk_sc1.dta")
head(bk_sc1)
str(bk_sc1)
urban_rural <- bk_sc1 %>%
    select(hhid14_9, hhid14, sc05)
urban_rural <- rename(urban_rural, "urban_rural" = sc05)
head(urban_rural)

demographic <- left_join(sex_age_marstat, urban_rural, by = c("hhid14_9","hhid14")) #merged
head(demographic)
str(demographic)
summary(demographic)

#Obesity (waist and bmi)

bus_us <- read.dta("bus_us.dta")
head(bus_us)
str(bus_us)
obesity <- bus_us %>%
    select(pidlink, us04, us06, us06a, us04x, us06x, us06ax) %>%
    mutate("height_m" = us04/100) %>%
    mutate("bmi" = us06 / (height_m^2))

obesity <- rename(obesity, "height_cm" = us04, "weight_kg" = us06, "waist" = us06a, "height_reason" = us04x, "weight_reason" = us06x, "waist_reason" = us06ax)
head(obesity)
summary(obesity)

#Hypertension from diagnose and using medication
hypertension_medication <- b3b_cd3 %>%
                select(pidlink, cdtype, cd05, cd09) %>%
                filter(cdtype == 'A')
hypertension_medication <- rename(hypertension_medication, "hypertension_diag" = cd05, "hyper_medication" = cd09)
head(hypertension_medication)
str(hypertension_medication)
summary(hypertension_medication)

#Hypertension from health measurement
head(bus_us)
hypertension <- bus_us %>%
    select(pidlink, us07a1, us07a2, us07b1, us07b2, us07c1, us07c2) %>%
    mutate("sistol" = (us07a1 + us07b1 + us07c1)/3,
           "diastol" = (us07a2 + us07b2 + us07c2)/3) %>%
    select(pidlink, sistol, diastol) %>%
    full_join(hypertension_medication, by = "pidlink") %>%
    select(-cdtype)

head(hypertension)
summary(hypertension)

#Education

b3a_dl1 <- read.dta("b3a_dl1.dta")
head(b3a_dl1)
education <- b3a_dl1 %>%
                select(pidlink, dl06)
education <- rename(education, "education" = dl06)
head(education)

# Depression

b3b_kp <- read.dta("b3b_kp.dta")
str(b3b_kp)
summary(b3b_kp)
head(b3b_kp)

#coding by separate into two categorized, depressing (+) and undepressing (-) then merge them
depressing <- subset(b3b_kp, kptype %in% c('A', 'B', 'C', 'D', 'F', 'G', 'I', 'J'))
undepressing <- subset(b3b_kp, kptype %in% c('E', 'H'))

depressing_score <- depressing %>%
                        mutate(score = revalue(kp02, c("1:Rarely or none (<= 1 day)" = 0,
                                                       "2:Some days (1-2 days)" = 1,
                                                       "3:Occasionally (3-4 days)" = 2,
                                                        "4:Most of the time (5-7 days)" = 3)))

undepressing_score <- undepressing %>%
                        mutate(score = revalue(kp02, c("1:Rarely or none (<= 1 day)" = 3,
                                                       "2:Some days (1-2 days)" = 2,
                                                       "3:Occasionally (3-4 days)" = 1,
                                                        "4:Most of the time (5-7 days)" = 0)))

depression_score_merged <- union(depressing_score, undepressing_score)

#aggregate sum of score each person
depression_score_merged$score <- as.integer(depression_score_merged$score)

depression <- depression_score_merged %>%
                    select(pidlink, score) %>%
                    group_by(pidlink) %>%
                    summarize_all(sum)
depression <- rename(depression, "depression_score" = score)
head(depression)
str(depression)
summary(depression)

"""# Merge all column into one single table"""

all_merged <- diabetes_medication %>%
    left_join(activity_categorized, by = "pidlink") %>%
    left_join(hypertension, by = "pidlink") %>%
    left_join(obesity, by = "pidlink") %>%
    left_join(education, by = "pidlink") %>%
    left_join(depression, by = "pidlink") %>%
    left_join(demographic, by = "pidlink") %>%
    select(-"hhid14_9.y", -"hhid14.y") %>%
    left_join(insurance, by = "pidlink")

head(all_merged)
str(all_merged)
summary(all_merged)

write.csv(all_merged, file = "unfiltered_numeric_dataset.csv")

"""# Data transofmation - filtering (outlier haven't been excluded yet), categorized numerical values, and recoding"""

# Age >= 45, bmi, waist, education, insurance and depression_score is not NA, education not in pesantren
# Maybe should exclude outlier in some continous variable also (height, weight, waist, sistol and diastol)

filtered <- all_merged %>%
            filter(age >= 45,
                   !is.na(bmi),
                   !is.na(waist),
                   !is.na(education),
                   !is.na(depression_score),
                   !is.na(insurance),
                   !education %in% c("14:Islamic School (pesantren)", "95:Other", "98:Don't Know", "99:MISSING")) %>%
            select(-waist_reason, -weight_reason, -height_reason, -cdtype, -height_cm, -weight_kg, -height_m)

head(filtered)
str(filtered)
summary(filtered)

write.csv(filtered, file = "numeric_dataset.csv")

#Checking the outliers in numeric data. Should we exclude outliers?

boxplot(filtered$age,
       filtered$bmi,
       filtered$waist,
       filtered$sistol,
       filtered$diastol,
       filtered$depression_score)

# Convert continous data to categorical data and change data type to ordered factors (ordinal data type)

dataset <- filtered %>%
            mutate(depression = as.factor(case_when(depression_score < 10 ~ "0:No",
                                          depression_score >= 10 ~ "1:Yes")),
                   depression = factor(depression, levels = c("0:No", "1:Yes")),
                   age_categorized = as.factor(case_when(age >= 45 & age <55 ~ "0:45-54",
                                               age >= 55 & age <65 ~ "1:55-64",
                                               age >= 65 & age <75 ~ "2:65-74",
                                               age >= 75 ~ "3:>=75")),
                   age_categorized = factor(age_categorized, ordered = TRUE, levels = c("0:45-54", "1:55-64", "2:65-74", "3:>=75")),
                   bmi_obesity = as.factor(case_when(bmi <18.5 ~ "0:Underweight",
                                           bmi >= 18.5 & bmi <23 ~ "1:Normal",
                                           bmi >= 23 & bmi <25 ~ "2:At risk",
                                           bmi >= 25 & bmi <30 ~ "3:Obese I",
                                           bmi >30 ~ "4:Obese II")),
                   bmi_obesity = factor(bmi_obesity, ordered = TRUE, levels = c("0:Underweight", "1:Normal", "2:At risk", "3:Obese I", "4:Obese II")),
                   waist_obesity = as.factor(case_when(waist <90 & sex == "1:Male" ~ "0:Normal",
                                             waist >=90 & sex == "1:Male" ~ "1:Obese",
                                             waist <80 & sex == "3:Female" ~ "0:Normal",
                                             waist >=80 & sex == "3:Female" ~ "1:Obese")),
                   waist_obesity = factor(waist_obesity, ordered = TRUE, levels = c("0:Normal", "1:Obese")),
                   hypertension = as.factor(case_when(sistol >= 140 | diastol >= 90 | hypertension_diag == "1:Yes"| hyper_medication == "1:Yes" ~ "1:Hypertension",
                                            TRUE ~ "0:Normal")),
                   hypertension = factor(hypertension, levels = c("0:Normal", "1:Hypertension")),
                   marstat_categorized = as.factor(revalue(marstat, c("2:Married" = "0:Married",
                                                                       "1:Not yet married" = "1:Others",
                                                                       "3:Separated" = "1:Others",
                                                                       "4:Divorced" = "1:Others",
                                                                       "5:Widowed" = "1:Others",
                                                                       "6:Cohabitate" = "1:Others"))),
                   marstat_categorized = factor(marstat_categorized, levels = c("0:Married", "1:Others")),
                   edu_categorized = as.factor(revalue(education, c("2:Elementary school" = "2:Rendah",
                                                                      "90:Kindergarten" = "2:Rendah",
                                                                      "11:Adult education A" = "2:Rendah",
                                                                      "17:School for Disabled" = "2:Rendah",
                                                                      "72:Islamic Elementary School (Madrasah Ibtidaiyah)" = "2:Rendah",
                                                                      "3:Junior high general" = "1:Menengah",
                                                                      "12:Adult education B" = "1:Menengah",
                                                                      "4:Junior high vocational" = "1:Menengah",
                                                                      "5:Senior high general" = "1:Menengah",
                                                                      "6:Senior high vocational" = "1:Menengah",
                                                                      "15:Adult education C" = "1:Menengah",
                                                                      "73:Islamic Junior/High School (Madrasah Tsanawiyah)" = "1:Menengah",
                                                                      "74:Islamic Senior/High School (Madrasah Tsanawiyah)" = "1:Menengah",
                                                                      "60:College (D1,D2,D3)" = "0:Tinggi",
                                                                      "13:Open university" = "0:Tinggi",
                                                                      "61:University S1" = "0:Tinggi",
                                                                      "62:University S2" = "0:Tinggi",
                                                                      "63:University S3" = "0:Tinggi"))),
                    edu_categorized = factor(edu_categorized, ordered = TRUE, levels = c("0:Tinggi", "1:Menengah", "2:Rendah")),
                    diabetes = as.factor(revalue(diabetes, c("3:No" = "0:No",
                                                              "1:Yes" = "1:Yes"))),
                    diabetes = factor(diabetes, levels = c("0:No", "1:Yes")),
                    urban_rural = as.factor(revalue(urban_rural, c("2:Rural" = "1:Rural",
                                                                   "1:Urban" = "0:Urban"))),
                    urban_rural = factor(urban_rural, levels = c("0:Urban", "1:Rural")),
                    sex = as.factor(revalue(sex, c("1:Male" = "0:Male",
                                                   "3:Female" = "1:Female"))),
                    sex = factor(sex, levels = c("0:Male", "1:Female")),
                    insurance = as.factor(revalue(insurance, c("3:No" = "0:No",
                                                              "1:Yes" = "1:Yes"))),
                    insurance = factor(insurance, levels = c("0:No", "1:Yes"))) %>%
                    select(-age, -depression_score, -bmi, -waist, -sistol, -diastol, -hypertension_diag, -hyper_medication, -marstat, -education, -hhid14_9.x, -hhid14.x, -medication)

dataset <- rename(dataset, "activity" = activity_cat,
                           "residence" = urban_rural,
                           "age" = age_categorized,
                           "marital" = marstat_categorized,
                           "education" = edu_categorized)

head(dataset)
str(dataset)
summary(dataset)

# Create a unordered factor for logistic regression analysis

dataset_unordered <- filtered %>%
            mutate(depression = as.factor(case_when(depression_score < 10 ~ "0:No",
                                          depression_score >= 10 ~ "1:Yes")),
                   depression = factor(depression, levels = c("0:No", "1:Yes")),
                   age_categorized = as.factor(case_when(age >= 45 & age <55 ~ "0:45-54",
                                               age >= 55 & age <65 ~ "1:55-64",
                                               age >= 65 & age <75 ~ "2:65-74",
                                               age >= 75 ~ "3:>=75")),
                   age_categorized = factor(age_categorized, levels = c("0:45-54", "1:55-64", "2:65-74", "3:>=75")),
                   bmi_obesity = as.factor(case_when(bmi <18.5 ~ "0:Underweight",
                                           bmi >= 18.5 & bmi <23 ~ "1:Normal",
                                           bmi >= 23 & bmi <25 ~ "2:At risk",
                                           bmi >= 25 & bmi <30 ~ "3:Obese I",
                                           bmi >30 ~ "4:Obese II")),
                   bmi_obesity = factor(bmi_obesity, levels = c("0:Underweight", "1:Normal", "2:At risk", "3:Obese I", "4:Obese II")),
                   waist_obesity = as.factor(case_when(waist <90 & sex == "1:Male" ~ "0:Normal",
                                             waist >=90 & sex == "1:Male" ~ "1:Obese",
                                             waist <80 & sex == "3:Female" ~ "0:Normal",
                                             waist >=80 & sex == "3:Female" ~ "1:Obese")),
                   waist_obesity = factor(waist_obesity, levels = c("0:Normal", "1:Obese")),
                   hypertension = as.factor(case_when(sistol >= 140 | diastol >= 90 | hypertension_diag == "1:Yes"| hyper_medication == "1:Yes" ~ "1:Hypertension",
                                            TRUE ~ "0:Normal")),
                   hypertension = factor(hypertension, levels = c("0:Normal", "1:Hypertension")),
                   marstat_categorized = as.factor(revalue(marstat, c("2:Married" = "0:Married",
                                                                       "1:Not yet married" = "1:Others",
                                                                       "3:Separated" = "1:Others",
                                                                       "4:Divorced" = "1:Others",
                                                                       "5:Widowed" = "1:Others",
                                                                       "6:Cohabitate" = "1:Others"))),
                   marstat_categorized = factor(marstat_categorized, levels = c("0:Married", "1:Others")),
                   edu_categorized = as.factor(revalue(education, c("2:Elementary school" = "2:Rendah",
                                                                      "90:Kindergarten" = "2:Rendah",
                                                                      "11:Adult education A" = "2:Rendah",
                                                                      "17:School for Disabled" = "2:Rendah",
                                                                      "72:Islamic Elementary School (Madrasah Ibtidaiyah)" = "2:Rendah",
                                                                      "3:Junior high general" = "1:Menengah",
                                                                      "12:Adult education B" = "1:Menengah",
                                                                      "4:Junior high vocational" = "1:Menengah",
                                                                      "5:Senior high general" = "1:Menengah",
                                                                      "6:Senior high vocational" = "1:Menengah",
                                                                      "15:Adult education C" = "1:Menengah",
                                                                      "73:Islamic Junior/High School (Madrasah Tsanawiyah)" = "1:Menengah",
                                                                      "74:Islamic Senior/High School (Madrasah Tsanawiyah)" = "1:Menengah",
                                                                      "60:College (D1,D2,D3)" = "0:Tinggi",
                                                                      "13:Open university" = "0:Tinggi",
                                                                      "61:University S1" = "0:Tinggi",
                                                                      "62:University S2" = "0:Tinggi",
                                                                      "63:University S3" = "0:Tinggi"))),
                    edu_categorized = factor(edu_categorized, levels = c("0:Tinggi", "1:Menengah", "2:Rendah")),
                    diabetes = as.factor(revalue(diabetes, c("3:No" = "0:No",
                                                              "1:Yes" = "1:Yes"))),
                    diabetes = factor(diabetes, levels = c("0:No", "1:Yes")),
                    urban_rural = as.factor(revalue(urban_rural, c("2:Rural" = "1:Rural",
                                                                   "1:Urban" = "0:Urban"))),
                    urban_rural = factor(urban_rural, levels = c("0:Urban", "1:Rural")),
                    sex = as.factor(revalue(sex, c("1:Male" = "0:Male",
                                                   "3:Female" = "1:Female"))),
                    sex = factor(sex, levels = c("0:Male", "1:Female")),
                    insurance = as.factor(revalue(insurance, c("3:No" = "0:No",
                                                              "1:Yes" = "1:Yes"))),
                    insurance = factor(insurance, levels = c("0:No", "1:Yes"))) %>%
                    select(-age, -depression_score, -bmi, -waist, -sistol, -diastol, -hypertension_diag, -hyper_medication, -marstat, -education, -hhid14_9.x, -hhid14.x, -medication)

dataset_unordered <- rename(dataset_unordered, "activity" = activity_cat,
                           "residence" = urban_rural,
                           "age" = age_categorized,
                           "marital" = marstat_categorized,
                           "education" = edu_categorized)

head(dataset_unordered)
str(dataset_unordered)
summary(dataset_unordered)

write.csv(dataset, file = "dataset.csv")

write.csv(dataset_unordered, file = "dataset_unordered.csv")

"""# Univariate analysis (proportion tables)"""

#Proportion table diabetes prevalence each independent variable groups

absolute_activity_db <- table(dataset$activity, dataset$diabetes, dnn = c("Activity", "DB"))
prop_activity_db <- round(prop.table(table(dataset$activity, dataset$diabetes, dnn = c("Activity", "DB")),1),digits=2)
absolute_activity_db
prop_activity_db

absolute_sex_db <- table(dataset$sex, dataset$diabetes, dnn = c("Sex", "DB"))
prop_sex_db <- round(prop.table(table(dataset$sex, dataset$diabetes, dnn = c("Sex", "DB")),1),digits=2)
absolute_sex_db
prop_sex_db

absolute_residence_db <- table(dataset$residence, dataset$diabetes, dnn = c("residence", "DB"))
prop_residence_db <- round(prop.table(table(dataset$residence, dataset$diabetes, dnn = c("residence", "DB")),1),digits=2)
absolute_residence_db
prop_residence_db

absolute_insurance_db <- table(dataset$insurance, dataset$diabetes, dnn = c("insurance", "DB"))
prop_insurance_db <- round(prop.table(table(dataset$insurance, dataset$diabetes, dnn = c("insurance", "DB")),1),digits=2)
absolute_insurance_db
prop_insurance_db

absolute_depression_db <- table(dataset$depression, dataset$diabetes, dnn = c("depression", "DB"))
prop_depression_db <- round(prop.table(table(dataset$depression, dataset$diabetes, dnn = c("depression", "DB")),1),digits=2)
absolute_depression_db
prop_depression_db

absolute_age_db <- table(dataset$age, dataset$diabetes, dnn = c("age", "DB"))
prop_age_db <- round(prop.table(table(dataset$age, dataset$diabetes, dnn = c("age", "DB")),1),digits=2)
absolute_age_db
prop_age_db

absolute_bmi_obesity_db <- table(dataset$bmi_obesity, dataset$diabetes, dnn = c("bmi_obesity", "DB"))
prop_bmi_obesity_db <- round(prop.table(table(dataset$bmi_obesity, dataset$diabetes, dnn = c("bmi_obesity", "DB")),1),digits=2)
absolute_bmi_obesity_db
prop_bmi_obesity_db

absolute_waist_obesity_db <- table(dataset$waist_obesity, dataset$diabetes, dnn = c("waist_obesity", "DB"))
prop_waist_obesity_db <- round(prop.table(table(dataset$waist_obesity, dataset$diabetes, dnn = c("waist_obesity", "DB")),1),digits=2)
absolute_waist_obesity_db
prop_waist_obesity_db

absolute_hypertension_db <- table(dataset$hypertension, dataset$diabetes, dnn = c("hypertension", "DB"))
prop_hypertension_db <- round(prop.table(table(dataset$hypertension, dataset$diabetes, dnn = c("hypertension", "DB")),1),digits=2)
absolute_hypertension_db
prop_hypertension_db

absolute_marital_db <- table(dataset$marital, dataset$diabetes, dnn = c("marital", "DB"))
prop_marital_db <- round(prop.table(table(dataset$marital, dataset$diabetes, dnn = c("marital", "DB")),1),digits=2)
absolute_marital_db
prop_marital_db

absolute_education_db <- table(dataset$education, dataset$diabetes, dnn = c("education", "DB"))
prop_education_db <- round(prop.table(table(dataset$education, dataset$diabetes, dnn = c("education", "DB")),1),digits=2)
absolute_education_db
prop_education_db

#Proportion table for physical activity each independent variable groups

absolute_sex_activity <- table(dataset$sex, dataset$activity, dnn = c("Sex", "activity"))
prop_sex_activity <- round(prop.table(table(dataset$sex, dataset$activity, dnn = c("Sex", "activity")),1),digits=2)
absolute_sex_activity
prop_sex_activity

absolute_residence_activity <- table(dataset$residence, dataset$activity, dnn = c("residence", "activity"))
prop_residence_activity <- round(prop.table(table(dataset$residence, dataset$activity, dnn = c("residence", "activity")),1),digits=2)
absolute_residence_activity
prop_residence_activity

absolute_insurance_activity <- table(dataset$insurance, dataset$activity, dnn = c("insurance", "activity"))
prop_insurance_activity <- round(prop.table(table(dataset$insurance, dataset$activity, dnn = c("insurance", "activity")),1),digits=2)
absolute_insurance_activity
prop_insurance_activity

absolute_depression_activity <- table(dataset$depression, dataset$activity, dnn = c("depression", "activity"))
prop_depression_activity <- round(prop.table(table(dataset$depression, dataset$activity, dnn = c("depression", "activity")),1),digits=2)
absolute_depression_activity
prop_depression_activity

absolute_age_activity <- table(dataset$age, dataset$activity, dnn = c("age", "activity"))
prop_age_activity <- round(prop.table(table(dataset$age, dataset$activity, dnn = c("age", "activity")),1),digits=2)
absolute_age_activity
prop_age_activity

absolute_bmi_obesity_activity <- table(dataset$bmi_obesity, dataset$activity, dnn = c("bmi_obesity", "activity"))
prop_bmi_obesity_activity <- round(prop.table(table(dataset$bmi_obesity, dataset$activity, dnn = c("bmi_obesity", "activity")),1),digits=2)
absolute_bmi_obesity_activity
prop_bmi_obesity_activity

absolute_waist_obesity_activity <- table(dataset$waist_obesity, dataset$activity, dnn = c("waist_obesity", "activity"))
prop_waist_obesity_activity <- round(prop.table(table(dataset$waist_obesity, dataset$activity, dnn = c("waist_obesity", "activity")),1),digits=2)
absolute_waist_obesity_activity
prop_waist_obesity_activity

absolute_hypertension_activity <- table(dataset$hypertension, dataset$activity, dnn = c("hypertension", "activity"))
prop_hypertension_activity <- round(prop.table(table(dataset$hypertension, dataset$activity, dnn = c("hypertension", "activity")),1),digits=2)
absolute_hypertension_activity
prop_hypertension_activity

absolute_marital_activity <- table(dataset$marital, dataset$activity, dnn = c("marital", "activity"))
prop_marital_activity <- round(prop.table(table(dataset$marital, dataset$activity, dnn = c("marital", "activity")),1),digits=2)
absolute_marital_activity
prop_marital_activity

absolute_education_activity <- table(dataset$education, dataset$activity, dnn = c("education", "activity"))
prop_education_activity <- round(prop.table(table(dataset$education, dataset$activity, dnn = c("education", "activity")),1),digits=2)
absolute_education_activity
prop_education_activity

"""# Bivariate analysis using chi square"""

# Bivariate analysis chi square using cleaned and prepared dataset for all independent variables to diabetes

marital_db_test <- chisq.test(dataset$marital, dataset$diabetes) #marital_status
print(marital_db_test)

sex_db_test <- chisq.test(dataset$sex, dataset$diabetes) #sex
print(sex_db_test)

edu_db_test <- chisq.test(dataset$education, dataset$diabetes) #education
print(edu_db_test)

residence_db_test <- chisq.test(dataset$residence, dataset$diabetes) #residence or urban_rural
print(residence_db_test)

insurance_db_test <- chisq.test(dataset$insurance, dataset$diabetes) #insurance
print(insurance_db_test)

activity_db_test <- chisq.test(dataset$activity, dataset$diabetes) #physical activity
print(activity_db_test)

depression_db_test <- chisq.test(dataset$depression, dataset$diabetes) #depression
print(depression_db_test)

age_db_test <- chisq.test(dataset$age, dataset$diabetes) #age
print(age_db_test)

bmi_db_test <- chisq.test(dataset$bmi_obesity, dataset$diabetes) #bmi
print(bmi_db_test)

waist_db_test <- chisq.test(dataset$waist_obesity, dataset$diabetes) #waist circumference
print(waist_db_test)

hypertension_db_test <- chisq.test(dataset$hypertension, dataset$diabetes) #hypertension
print(hypertension_db_test)

# Bivariate analysis chi square using cleaned and prepared dataset for all independent variables to physical activity

marital_act_test <- chisq.test(dataset$marital, dataset$activity) #marital_status
print(marital_act_test)

sex_act_test <- chisq.test(dataset$sex, dataset$activity) #sex
print(sex_act_test)

edu_act_test <- chisq.test(dataset$education, dataset$activity) #education
print(edu_act_test)

residence_act_test <- chisq.test(dataset$residence, dataset$activity) #residence or urban_rural
print(residence_act_test)

insurance_act_test <- chisq.test(dataset$insurance, dataset$activity) #insurance
print(insurance_act_test)

activity_act_test <- chisq.test(dataset$activity, dataset$activity) #physical activity
print(activity_act_test)

depression_act_test <- chisq.test(dataset$depression, dataset$activity) #depression
print(depression_act_test)

age_act_test <- chisq.test(dataset$age, dataset$activity) #age
print(age_act_test)

bmi_act_test <- chisq.test(dataset$bmi_obesity, dataset$activity) #bmi
print(bmi_act_test)

waist_act_test <- chisq.test(dataset$waist_obesity, dataset$activity) #waist circumference
print(waist_act_test)

hypertension_act_test <- chisq.test(dataset$hypertension, dataset$activity) #hypertension
print(hypertension_act_test)

"""# Measure of Association - Prevalence Ratio (PR)"""

# Reverse order factor level just for calculating Prevalence Ratio, because positive exposures and outcomes come first (PR)
dataset_reversed <- dataset %>%
                    mutate(diabetes = factor(diabetes, levels = rev(levels(diabetes))),
                           activity = factor(activity, levels = rev(levels(activity))),
                           insurance = factor(insurance, levels = rev(levels(insurance))),
                           marital = factor(marital, levels = rev(levels(marital))),
                           sex = factor(sex, levels = rev(levels(sex))),
                           residence = factor(residence, levels = rev(levels(residence))),
                           depression = factor(depression, levels = rev(levels(depression))),
                           age = factor(age, levels = rev(levels(age))),
                           bmi_obesity = factor(bmi_obesity, levels = rev(levels(bmi_obesity))),
                           waist_obesity = factor(waist_obesity, levels = rev(levels(waist_obesity))),
                           hypertension = factor(hypertension, levels = rev(levels(hypertension))),
                           education = factor(education, levels = rev(levels(education))))
summary(dataset_reversed)

#Create contingency table (2 by 2 table) for PR
ins_db_table <- table(dataset_reversed$insurance, dataset_reversed$diabetes)
res_db_table <- table(dataset_reversed$residence, dataset_reversed$diabetes)
dep_db_table <- table(dataset_reversed$depression, dataset_reversed$diabetes)
waist_db_table <- table(dataset_reversed$waist_obesity, dataset_reversed$diabetes)
hyp_db_table <- table(dataset_reversed$hypertension, dataset_reversed$diabetes)
mar_db_table <- table(dataset_reversed$marital, dataset_reversed$diabetes)
sex_db_table <- table(dataset_reversed$sex, dataset_reversed$diabetes)

# Calculate PR for 2 by 2 table

pr_insurance <- epi.2by2(ins_db_table, method = "cross.sectional", conf.level = 0.95, units = 100,
   outcome = "as.columns")
pr_residence <- epi.2by2(res_db_table, method = "cross.sectional", conf.level = 0.95, units = 100,
   outcome = "as.columns")
pr_depression <- epi.2by2(dep_db_table, method = "cross.sectional", conf.level = 0.95, units = 100,
   outcome = "as.columns")
pr_waist <- epi.2by2(waist_db_table, method = "cross.sectional", conf.level = 0.95, units = 100,
   outcome = "as.columns")
pr_hypertension <- epi.2by2(hyp_db_table, method = "cross.sectional", conf.level = 0.95, units = 100,
   outcome = "as.columns")
pr_marital <- epi.2by2(mar_db_table, method = "cross.sectional", conf.level = 0.95, units = 100,
   outcome = "as.columns")
pr_sex <- epi.2by2(sex_db_table, method = "cross.sectional", conf.level = 0.95, units = 100,
   outcome = "as.columns")

pr_insurance
pr_residence
pr_depression
pr_waist
pr_hypertension
pr_marital
pr_sex

# Calculate PR for multiple exposure groups using refference group

# PR physical activity
prevalence_activity <- dataset %>%
                select(activity, diabetes) %>%
                group_by(activity, diabetes) %>%
                filter(diabetes == "1:Yes") %>%
                count() %>%
                rename("have_db" = n)

total_activity <- dataset %>%
                select(activity) %>%
                group_by(activity) %>%
                count() %>%
                rename("total" = n)

activity_table_pr <- left_join(prevalence_activity, total_activity, by = "activity")

prev_activity <- activity_table_pr %>%
                    mutate(prevalence = have_db / total)

reff_activity_table <- prev_activity %>%
                filter(activity == "0:High") %>%
                select(prevalence)
reff_activity <- reff_activity_table$prevalence

pr_activity <- prev_activity %>%
                mutate(pr = prevalence / reff_activity)

# PR bmi obesity
prevalence_bmi_obesity <- dataset %>%
                select(bmi_obesity, diabetes) %>%
                group_by(bmi_obesity, diabetes) %>%
                filter(diabetes == "1:Yes") %>%
                count() %>%
                rename("have_db" = n)

total_bmi_obesity <- dataset %>%
                select(bmi_obesity) %>%
                group_by(bmi_obesity) %>%
                count() %>%
                rename("total" = n)

bmi_obesity_table_pr <- left_join(prevalence_bmi_obesity, total_bmi_obesity, by = "bmi_obesity")

prev_bmi_obesity <- bmi_obesity_table_pr %>%
                    mutate(prevalence = have_db / total)

reff_bmi_obesity_table <- prev_bmi_obesity %>%
                filter(bmi_obesity == "0:Underweight") %>%
                select(prevalence)

reff_bmi_obesity <- reff_bmi_obesity_table$prevalence

pr_bmi_obesity <- prev_bmi_obesity %>%
                mutate(pr = prevalence / reff_bmi_obesity)

# PR age
prevalence_age <- dataset %>%
                select(age, diabetes) %>%
                group_by(age, diabetes) %>%
                filter(diabetes == "1:Yes") %>%
                count() %>%
                rename("have_db" = n)

total_age <- dataset %>%
                select(age) %>%
                group_by(age) %>%
                count() %>%
                rename("total" = n)

age_table_pr <- left_join(prevalence_age, total_age, by = "age")

prev_age <- age_table_pr %>%
                    mutate(prevalence = have_db / total)

reff_age_table <- prev_age %>%
                filter(age == "0:45-54") %>%
                select(prevalence)

reff_age <- reff_age_table$prevalence

pr_age <- prev_age %>%
                mutate(pr = prevalence / reff_age)

# PR education
prevalence_education <- dataset %>%
                select(education, diabetes) %>%
                group_by(education, diabetes) %>%
                filter(diabetes == "1:Yes") %>%
                count() %>%
                rename("have_db" = n)

total_education <- dataset %>%
                select(education) %>%
                group_by(education) %>%
                count() %>%
                rename("total" = n)

education_table_pr <- left_join(prevalence_education, total_education, by = "education")

prev_education <- education_table_pr %>%
                    mutate(prevalence = have_db / total)

reff_education_table <- prev_education %>%
                filter(education == "0:Tinggi") %>%
                select(prevalence)

reff_education <- reff_education_table$prevalence

pr_education <- prev_education %>%
                mutate(pr = prevalence / reff_education)

pr_activity
pr_bmi_obesity
pr_age
pr_education

"""# Multivariate analysis - Logistic Regression !"""

# Take all variable into account to create a totally complete models
logit_complete <- glm(diabetes ~ activity + hypertension + waist_obesity + bmi_obesity + age + insurance + residence + education + marital + sex + depression, data=dataset, family=binomial(link="logit"))
summary(logit_complete)

# Take only signifficant variable from previous chi square test into account
logit_filtered <- glm(diabetes ~ activity + hypertension + waist_obesity + bmi_obesity + age + insurance + residence + education, data=dataset, family=binomial(link="logit"))
summary(logit_filtered)

# Add interaction between sex variable and some independent variables to create a better models
logit_interaction <- glm(diabetes ~ activity + hypertension + waist_obesity + bmi_obesity + age + insurance + residence + education + marital + sex + depression
                         + sex*activity + sex*bmi_obesity + sex*education + sex*depression, data=dataset_unordered, family=binomial(link="logit"))
summary(logit_interaction)
BIC(logit_interaction)